version: "3.8"

services:
  web:
    build: ./app
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    container_name: sqlite-db
    volumes:
      - db-data:/root/db

volumes:
  db-data:
