version: "3.8"
 
services:
  web:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my-network
 
  db:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abc12345
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: Abc12345
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network
 
networks:
  my-network:
 
volumes:
  db-data: